server:
  port: 8191
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Hansini97/microservices-config-store-second
          default-label: master
          search-paths:
            - 'service-config/*service'
